set-option -g history-limit 1000000000
set -g mouse on
set -g set-clipboard on

# Jump to previous word
bind-key -n M-Left send-keys M-b
# Jump to next word
bind-key -n M-Right send-keys M-f

setw -g mode-keys vi

unbind Space
bind y next-layout

# Use 'v' to begin selection like in Vim
bind-key -T copy-mode-vi v send-keys -X begin-selection

# OS-Specific Clipboard Handling
if-shell "uname | grep -q Darwin" {
    # Mac (pbcopy)
    bind-key -T copy-mode-vi y send-keys -X copy-pipe "pbcopy"
    bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe "pbcopy"
    bind-key -T copy-mode-vi Enter send-keys -X copy-pipe "pbcopy"
} {
    # Linux (xclip - ensure it's installed on your remote nodes)
    bind-key -T copy-mode-vi y send-keys -X copy-pipe "xclip -in -selection clipboard"
    bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe "xclip -in -selection clipboard"
    bind-key -T copy-mode-vi Enter send-keys -X copy-pipe "xclip -in -selection clipboard"
}

# Stay in copy mode after making a selection with the mouse
# This prevents the jump to the bottom/prompt
unbind -T copy-mode-vi MouseDragEnd1Pane
